In [1]:
import pandas as pd

In [2]:
file = pd.read_excel('dividends.xlsx', skiprows=13)
file

,Unnamed: 0,Movimentação,Liquidação,Lançamento,Unnamed: 4,Valor (R$),Saldo (R$)
0,NaN,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,NaN,-3512.32,204.72
1,NaN,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,NaN,3536,3717.04
2,NaN,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,NaN,0.01,181.04
3,NaN,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,NaN,0.03,181.03
4,NaN,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,NaN,2.38,181
5,NaN,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,NaN,3.45,178.62
6,NaN,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,NaN,0.85,175.17
7,NaN,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,NaN,0.43,174.32
8,NaN,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,NaN,-888.19,173.89
9,NaN,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,NaN,0.95,1062.08
10,NaN,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,NaN,3.85,1061.13
11,NaN,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,NaN,0.1,1057.28
12,NaN,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,NaN,0.39,1057.18
13,NaN,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,NaN,0.19,1056.79
14,NaN,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,NaN,0.21,1056.6
15,NaN,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,NaN,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Lançamentos futuros,NaN,NaN,NaN,NaN,NaN
18,NaN,Movimentação,Liquidação,Lançamento,NaN,Valor (R$),Saldo (R$)
19,NaN,NaN,NaN,Não há lançamentos para o período,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN,NaN
22,NaN,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Importante:\n,NaN,NaN,NaN,NaN,NaN
25,NaN,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN,NaN
26,NaN,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN,NaN
27,NaN,desatualizada.\n,NaN,NaN,NaN,NaN,NaN
28,NaN,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN,NaN
29,NaN,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN,NaN
30,NaN,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,"Atendimento ao cliente: +55 11 3003-5465, +55 ...",NaN,NaN
31,NaN,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN,NaN
32,NaN,SAO PAULO | SP,NaN,NaN,Ouvidoria: 0800-722-3730.,NaN,NaN
33,NaN,CEP: 04538-132,NaN,NaN,"Dias úteis, de segunda a sexta-feira, das 9h à...",NaN,NaN
34,NaN,CNPJ: 13.434.335/0001-60,NaN,NaN,https://www.rico.com.br/,NaN,NaN

In [3]:
file = file.iloc[:, [1,2,3,5,6]]
file

,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
0,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN
17,Lançamentos futuros,NaN,NaN,NaN,NaN
18,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
19,NaN,NaN,Não há lançamentos para o período,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN
22,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,Importante:\n,NaN,NaN,NaN,NaN
25,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN
26,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN
27,desatualizada.\n,NaN,NaN,NaN,NaN
28,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN
29,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN
30,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,NaN,NaN
31,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN
32,SAO PAULO | SP,NaN,NaN,NaN,NaN
33,CEP: 04538-132,NaN,NaN,NaN,NaN
34,CNPJ: 13.434.335/0001-60,NaN,NaN,NaN,NaN

In [4]:
file = file.rename(columns={'Valor (R$)': 'Movement'})
file

,Movimentação,Liquidação,Lançamento,Movement,Saldo (R$)
0,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN
17,Lançamentos futuros,NaN,NaN,NaN,NaN
18,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
19,NaN,NaN,Não há lançamentos para o período,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN
22,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,Importante:\n,NaN,NaN,NaN,NaN
25,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN
26,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN
27,desatualizada.\n,NaN,NaN,NaN,NaN
28,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN
29,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN
30,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,NaN,NaN
31,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN
32,SAO PAULO | SP,NaN,NaN,NaN,NaN
33,CEP: 04538-132,NaN,NaN,NaN,NaN
34,CNPJ: 13.434.335/0001-60,NaN,NaN,NaN,NaN

In [5]:
file.columns = ['movement_date', 'clearning_date','description','movement','balance']
file

,movement_date,clearning_date,description,movement,balance
0,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN
17,Lançamentos futuros,NaN,NaN,NaN,NaN
18,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
19,NaN,NaN,Não há lançamentos para o período,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN
22,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,Importante:\n,NaN,NaN,NaN,NaN
25,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN
26,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN
27,desatualizada.\n,NaN,NaN,NaN,NaN
28,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN
29,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN
30,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,NaN,NaN
31,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN
32,SAO PAULO | SP,NaN,NaN,NaN,NaN
33,CEP: 04538-132,NaN,NaN,NaN,NaN
34,CNPJ: 13.434.335/0001-60,NaN,NaN,NaN,NaN

In [6]:
import datetime as dt

first_null = file['movement_date'].isna().argmax()
file = file.iloc[:first_null
                 ]
file

,movement_date,clearning_date,description,movement,balance
0,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39

In [7]:
file['movement_date'] = pd.to_datetime(file['movement_date'])
file['clearning_date'] = pd.to_datetime(file['clearning_date'])
file['movement_date'] = file['movement_date'].dt.date
file['clearning_date'] = file['clearning_date'].dt.date
file

/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/1642493696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file['movement_date'] = pd.to_datetime(file['movement_date'])
/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/1642493696.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file['clearning_date'] = pd.to_datetime(file['clearning_date'])
/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/1642493696.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file['movement_date'] = file['movement_date'].dt.date
/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/1642493696.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file['clearning_date'] = file['clearning_date'].dt.date

,movement_date,clearning_date,description,movement,balance
0,2026-02-04,2026-02-06,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04,2026-02-04,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28,2026-01-28,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28,2026-01-28,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21,2026-01-21,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21,2026-01-21,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19,2026-01-21,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19,2026-01-19,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15,2026-01-15,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14,2026-01-14,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13,2026-01-13,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07,2026-01-09,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39

In [8]:
third_string = file['description'][2]
third_string.split()[0]
file['income_type'] = file['description'].str.split().str[0]
file

/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/860508883.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file['income_type'] = file['description'].str.split().str[0]

,movement_date,clearning_date,description,movement,balance,income_type
0,2026-02-04,2026-02-06,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72,OPERAÇÕES
1,2026-02-04,2026-02-04,Transferência recebida da conta digital,3536,3717.04,Transferência
2,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04,JUROS
3,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03,JUROS
4,2026-01-28,2026-01-28,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181,JUROS
5,2026-01-28,2026-01-28,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62,DIVIDENDOS
6,2026-01-21,2026-01-21,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17,JUROS
7,2026-01-21,2026-01-21,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32,DIVIDENDOS
8,2026-01-19,2026-01-21,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89,OPERAÇÕES
9,2026-01-19,2026-01-19,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08,JUROS
10,2026-01-15,2026-01-15,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13,DIVIDENDOS
11,2026-01-14,2026-01-14,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28,JUROS
12,2026-01-13,2026-01-13,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18,JUROS
13,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79,JUROS
14,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6,JUROS
15,2026-01-07,2026-01-09,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39,OPERAÇÕES

In [9]:
word = file['description'][2].split()[-3]
word

'ITUB4'

In [10]:
filtered = file[file['income_type'].isin(['JUROS','DIVIDENDOS'])]
filtered['ticker'] = filtered['description'].str.split().str[-3]
filtered['quantity'] = filtered['description'].str.split().str[-1]
filtered

/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/237639274.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['ticker'] = filtered['description'].str.split().str[-3]
/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/237639274.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['quantity'] = filtered['description'].str.split().str[-1]

,movement_date,clearning_date,description,movement,balance,income_type,ticker,quantity
2,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04,JUROS,ITUB4,1
3,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03,JUROS,BBDC4,2
4,2026-01-28,2026-01-28,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181,JUROS,TAEE4,20
5,2026-01-28,2026-01-28,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62,DIVIDENDOS,TAEE4,20
6,2026-01-21,2026-01-21,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17,JUROS,TIMS3,5
7,2026-01-21,2026-01-21,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32,DIVIDENDOS,OXYP34,3
9,2026-01-19,2026-01-19,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08,JUROS,CPLE3,3
10,2026-01-15,2026-01-15,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13,DIVIDENDOS,MOOO34,1
11,2026-01-14,2026-01-14,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28,JUROS,EMBJ3,1
12,2026-01-13,2026-01-13,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18,JUROS,LREN3,2
13,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79,JUROS,B3SA3,3
14,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6,JUROS,B3SA3,3

In [11]:
filtered['quantity'] = filtered['quantity'].astype('int32')
filtered['movement'] = filtered['movement'].astype('float64')
filtered['individual_movement'] = (filtered['movement'] / filtered['quantity']).round(2)
filtered
filtered

/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/3041554651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['quantity'] = filtered['quantity'].astype('int32')
/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/3041554651.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['movement'] = filtered['movement'].astype('float64')
/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_7135/3041554651.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['individual_movement'] = (filtered['movement'] / filtered['quantity']).round(2)

,movement_date,clearning_date,description,movement,balance,income_type,ticker,quantity,individual_movement
2,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04,JUROS,ITUB4,1,0.01
3,2026-02-02,2026-02-02,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03,JUROS,BBDC4,2,0.02
4,2026-01-28,2026-01-28,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181,JUROS,TAEE4,20,0.12
5,2026-01-28,2026-01-28,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62,DIVIDENDOS,TAEE4,20,0.17
6,2026-01-21,2026-01-21,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17,JUROS,TIMS3,5,0.17
7,2026-01-21,2026-01-21,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32,DIVIDENDOS,OXYP34,3,0.14
9,2026-01-19,2026-01-19,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08,JUROS,CPLE3,3,0.32
10,2026-01-15,2026-01-15,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13,DIVIDENDOS,MOOO34,1,3.85
11,2026-01-14,2026-01-14,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.10,1057.28,JUROS,EMBJ3,1,0.10
12,2026-01-13,2026-01-13,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18,JUROS,LREN3,2,0.20
13,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79,JUROS,B3SA3,3,0.06
14,2026-01-12,2026-01-12,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6,JUROS,B3SA3,3,0.07

In [13]:
# TODO: Add dividend ID logic, SQL load logic, 
# TODO: Load historical dividends

historical = pd.read_excel('dividends_historical.xlsx')
historical

,dividend_id,dividend_date,ticker,type,dividend,total,quantity,portfolio
0,NaN,2024-08-21,AAPL34,DIVIDENDOS,0.045000,0.09,2,LEGEND
1,NaN,2024-10-03,BOAC34,DIVIDENDOS,0.230000,0.23,1,LEGEND
2,NaN,2024-11-21,AXPB34,DIVIDENDOS,0.260000,0.26,1,LEGEND
3,NaN,2024-11-22,AAPL34,DIVIDENDOS,0.045000,0.09,2,LEGEND
4,NaN,2024-12-17,CHVX34,DIVIDENDOS,0.650000,1.30,2,LEGEND
...,...,...,...,...,...,...,...,...
149,NaN,2025-12-16,UNIP6,DIVIDENDOS,0.443333,1.33,3,RENDA
150,NaN,2025-12-16,UNIP6,DIVIDENDOS,6.030000,18.09,3,RENDA
151,NaN,2025-12-22,PETR4,DIVIDENDOS,0.200000,1.80,9,RENDA
152,NaN,2025-12-22,PETR4,JUROS,0.114444,1.03,9,RENDA
153,NaN,2025-12-30,BRAP4,DIVIDENDOS,0.656667,3.94,6,RENDA

In [14]:
historical_edited = historical.copy()
historical_edited['dividend_date'] = historical_edited['dividend_date'].dt.date
historical_edited['dividend'] = historical_edited['dividend'].round(2)
historical_edited['total'] = historical_edited['total'].round(2)
historical_edited

,dividend_id,dividend_date,ticker,type,dividend,total,quantity,portfolio
0,NaN,2024-08-21,AAPL34,DIVIDENDOS,0.04,0.09,2,LEGEND
1,NaN,2024-10-03,BOAC34,DIVIDENDOS,0.23,0.23,1,LEGEND
2,NaN,2024-11-21,AXPB34,DIVIDENDOS,0.26,0.26,1,LEGEND
3,NaN,2024-11-22,AAPL34,DIVIDENDOS,0.04,0.09,2,LEGEND
4,NaN,2024-12-17,CHVX34,DIVIDENDOS,0.65,1.30,2,LEGEND
...,...,...,...,...,...,...,...,...
149,NaN,2025-12-16,UNIP6,DIVIDENDOS,0.44,1.33,3,RENDA
150,NaN,2025-12-16,UNIP6,DIVIDENDOS,6.03,18.09,3,RENDA
151,NaN,2025-12-22,PETR4,DIVIDENDOS,0.20,1.80,9,RENDA
152,NaN,2025-12-22,PETR4,JUROS,0.11,1.03,9,RENDA
153,NaN,2025-12-30,BRAP4,DIVIDENDOS,0.66,3.94,6,RENDA

In [17]:
import pandas as pd
import numpy as np
import uuid
from typing import Set

def add_validated_dividend_id_for_missing_robust(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generates unique UUIDs only for rows where 'dividend_id' is missing (NaN/None),
    ensuring no collision and explicitly handling data types to prevent warnings.
    """
    df_copy = df.copy()
    
    # 1. Ensure the 'dividend_id' column exists, using 'object' dtype
    if 'dividend_id' not in df_copy.columns:
        # Create the column and immediately set its type to 'object' (string)
        df_copy['t_id'] = pd.Series([np.nan] * len(df_copy), dtype='object')
        print("💡 'dividend_id' column created as type 'object'.")
    else:
        # If it exists, cast it to 'object' to handle any prior float/mixed inference
        df_copy['dividend_id'] = df_copy['dividend_id'].astype('object')
        
    # 2. Identify the rows where 'dividend_id' is missing
    missing_mask = df_copy['dividend_id'].isna()
    num_missing = missing_mask.sum()
    
    if num_missing == 0:
        print("✅ No missing 'dividend_id' values found. DataFrame returned unchanged.")
        return df_copy
    
    # 3. Create a set of all currently existing, VALID IDs for collision check
    # Note: We can safely use .astype(str) here, as all IDs are non-NaN strings now.
    existing_ids: Set[str] = set(df_copy['dividend_id'].dropna())
    
    print(f"Starting ID generation for {num_missing} missing rows. {len(existing_ids)} existing IDs found.")
    
    # 4. Generate new IDs 
    new_ids = []
    for _ in range(num_missing):
        unique_id = None
        while True:
            candidate_id = uuid.uuid4().hex
            if candidate_id not in existing_ids:
                unique_id = candidate_id
                existing_ids.add(unique_id)
                break
        new_ids.append(unique_id)
        
    # 5. Apply the new IDs only to the missing rows
    df_copy.loc[missing_mask, 'dividend_id'] = new_ids

    print(f"✅ Successfully generated and assigned {num_missing} new, non-conflicting IDs.")
    return df_copy

In [18]:
historical_edited = add_validated_dividend_id_for_missing_robust(historical_edited)
historical_edited

Starting ID generation for 154 missing rows. 0 existing IDs found.
✅ Successfully generated and assigned 154 new, non-conflicting IDs.

,dividend_id,dividend_date,ticker,type,dividend,total,quantity,portfolio
0,b68d436347894dc38243420a7b61353c,2024-08-21,AAPL34,DIVIDENDOS,0.04,0.09,2,LEGEND
1,21486c6935864bd3af6524bfbc8392ad,2024-10-03,BOAC34,DIVIDENDOS,0.23,0.23,1,LEGEND
2,342e6cf2feb1421f9b8077e42b449158,2024-11-21,AXPB34,DIVIDENDOS,0.26,0.26,1,LEGEND
3,d9e4a15b8bfc4930a212e35513bf84f4,2024-11-22,AAPL34,DIVIDENDOS,0.04,0.09,2,LEGEND
4,742c35ccb6ff4845a9acb07d6f7bbcf0,2024-12-17,CHVX34,DIVIDENDOS,0.65,1.30,2,LEGEND
...,...,...,...,...,...,...,...,...
149,fe9b870d065b4bea85c98b4a7d1e1632,2025-12-16,UNIP6,DIVIDENDOS,0.44,1.33,3,RENDA
150,c7edcdcfddbf478194372266c85bf3b3,2025-12-16,UNIP6,DIVIDENDOS,6.03,18.09,3,RENDA
151,d347782bdfd641458c7489f652bd4b54,2025-12-22,PETR4,DIVIDENDOS,0.20,1.80,9,RENDA
152,e87cdf5920f542eaa08d307a83e9a064,2025-12-22,PETR4,JUROS,0.11,1.03,9,RENDA
153,33102508b2cf4eb3a0e37345f09ddeb1,2025-12-30,BRAP4,DIVIDENDOS,0.66,3.94,6,RENDA

In [21]:
historical_edited.to_csv('dividend_history2.csv', index=False)

In [2]:
import psycopg2
import pandas as pd 

# from io import StringIO

# buffer = StringIO()

# df.to_csv(buffer, header=False, index=False)

# buffer.seek(0)

# columns = df.columns.to_list()

# Use database to simplify 

import pandas as pd
import numpy as np
import psycopg2
import os

# --- Configuration (Use your environment variables) ---
DB_HOST = os.environ.get("host")
DB_NAME = os.environ.get("dbname")
DB_USER = os.environ.get("user")
DB_PASSWORD = os.environ.get("password")
DB_PORT = 5432

connection = None
trades_df = pd.DataFrame() # Initialize an empty DataFrame

try:
    # 1. Establish the connection
    print(f"Connecting to the '{DB_NAME}' database...")
    connection = psycopg2.connect(
        host=DB_HOST,
        database=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD,
        port=DB_PORT
    )
    
    # 2. Define the SQL query
    # Selects all columns (*) and all rows from the specified table.
    sql_query = f"SELECT * FROM trades;"
    
    # 3. Use pandas to execute the query and read directly into a DataFrame
    print(f"Executing query: {sql_query}")
    trades_df = pd.read_sql_query(
        sql_query, 
        connection # pandas handles the cursor and fetching internally
    )
    
    # 4. Success message and data inspection
    print("\n--- ✅ Data Extraction Successful ---")
    print(f"Table 'trades' loaded into DataFrame.")
    print(f"DataFrame shape: {trades_df.shape}")
    print("\n--- DataFrame Head ---")
    print(trades_df.head())
    
except Exception as e:
    print(f"❌ Database connection or query error: {e}")
    trades_df = pd.DataFrame() # Ensure DF is empty on failure

finally:
    # Always close the connection
    if connection:
        connection.close()
        print("\nDatabase connection closed.")

Connecting to the 'postgres' database...
Executing query: SELECT * FROM trades;

/var/folders/sb/9vz_k9ms0tlfjj31q9q03hp00000gn/T/ipykernel_9275/2300018004.py:48: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  trades_df = pd.read_sql_query(

--- ✅ Data Extraction Successful ---
Table 'trades' loaded into DataFrame.
DataFrame shape: (165, 10)

--- DataFrame Head ---
                           trade_id        date side  ticker  \
0  db78c1263fa74a9da9688ad71a5c691d  2024-06-25  BUY  AAPL34
1  84071eba399a4a968380b81629222418  2024-07-24  BUY  OXYP34
2  bb06f3e80cac4524a99f9f0267a9848b  2024-08-22  BUY  BERK34
3  49c1acd5f8e540a3b5854b300344ea6b  2024-08-22  BUY  BOAC34
4  9101d965779e4a97a522e480d8f70291  2024-09-30  BUY  AXPB34

              asset  quantity   price   total   fee portfolio
0         APPLE DRN         2   57.30  114.60  0.00    LEGEND
1  OCCIDENT PTR DRN         3   56.45  169.35  0.05    LEGEND
2     BERKSHIRE DRN         3  124.39  373.17  0.11    LEGEND
3  BANK AMERICA DRN         1   54.57   54.57  0.02    LEGEND
4  AMERICAN EXP DRN         1  147.14  147.14  0.04    LEGEND

Database connection closed.

In [3]:
trades_df

,trade_id,date,side,ticker,asset,quantity,price,total,fee,portfolio
0,db78c1263fa74a9da9688ad71a5c691d,2024-06-25,BUY,AAPL34,APPLE DRN,2,57.30,114.60,0.00,LEGEND
1,84071eba399a4a968380b81629222418,2024-07-24,BUY,OXYP34,OCCIDENT PTR DRN,3,56.45,169.35,0.05,LEGEND
2,bb06f3e80cac4524a99f9f0267a9848b,2024-08-22,BUY,BERK34,BERKSHIRE DRN,3,124.39,373.17,0.11,LEGEND
3,49c1acd5f8e540a3b5854b300344ea6b,2024-08-22,BUY,BOAC34,BANK AMERICA DRN,1,54.57,54.57,0.02,LEGEND
4,9101d965779e4a97a522e480d8f70291,2024-09-30,BUY,AXPB34,AMERICAN EXP DRN,1,147.14,147.14,0.04,LEGEND
...,...,...,...,...,...,...,...,...,...,...
160,c67e3fe0c72146858d2a0df48d3fe074,2026-01-02,SELL,TIMS3,TIM ON EDJ NM,5,21.50,107.50,-0.01,VECTOR
161,7144a090db6649cb8ac93e7e52de05c5,2026-01-02,SELL,TOTS3,TOTVS ON NM,1,41.60,41.60,-0.01,VECTOR
162,9f4c79c6a79942d899dd58d64487792e,2026-02-04,BUY,BERK34,BERKSHIRE DRN,9,128.93,1160.37,0.36,LEGEND
163,5b57b815ce4a46b5a8ef6b8010fa64f9,2026-02-04,BUY,UNIP6,UNIPAR PNB,18,64.99,1169.82,0.36,RENDA
164,d6ba25da9bad4196a07207a977f14324,2026-02-04,BUY,UNHH34,UNITEDHEALTH DRN,56,21.09,1181.04,0.37,VECTOR

In [9]:
list_tickers = trades_df.copy()
list_tickers = list_tickers[['ticker','asset']]
list_tickers = list_tickers.drop_duplicates(subset='ticker')

In [10]:
list_tickers

     ticker             asset
0    AAPL34         APPLE DRN
1    OXYP34  OCCIDENT PTR DRN
2    BERK34     BERKSHIRE DRN
3    BOAC34  BANK AMERICA DRN
4    AXPB34  AMERICAN EXP DRN
..      ...               ...
142   CSNA3   SID NACIONAL ON
143   UGPA3    ULTRAPAR ON NM
145   VBBR3       VIBRA ON NM
146   WEGE3      WEG ON ED NM
147   MBRF3    MARFRIG ON NM

[68 rows x 2 columns]

In [11]:
import yfinance as yf

def get_stock_sector(ticker_symbol):
    try:
        # For B3 stocks, add '.SA' (e.g., 'AAPL34.SA' or 'PETR4.SA')
        ticker = yf.Ticker(ticker_symbol)
        info = ticker.info
        
        sector = info.get('sector', 'Unknown')
        industry = info.get('industry', 'Unknown')
        
        return sector, industry
    except Exception as e:
        return None, str(e)

# Example for Apple BDR in Brazil
sector, industry = get_stock_sector("AAPL34.SA")
print(f"Sector: {sector} | Industry: {industry}")

Sector: Technology | Industry: Consumer Electronics

In [ ]:
list_tickers['ticker_search'] = list_tickers['ticker'] + ".SA"

     ticker             asset ticker_search
0    AAPL34         APPLE DRN     AAPL34.SA
1    OXYP34  OCCIDENT PTR DRN     OXYP34.SA
2    BERK34     BERKSHIRE DRN     BERK34.SA
3    BOAC34  BANK AMERICA DRN     BOAC34.SA
4    AXPB34  AMERICAN EXP DRN     AXPB34.SA
..      ...               ...           ...
142   CSNA3   SID NACIONAL ON      CSNA3.SA
143   UGPA3    ULTRAPAR ON NM      UGPA3.SA
145   VBBR3       VIBRA ON NM      VBBR3.SA
146   WEGE3      WEG ON ED NM      WEGE3.SA
147   MBRF3    MARFRIG ON NM       MBRF3.SA

[68 rows x 3 columns]

In [15]:
list_tickers[['sector','industry']] = list_tickers['ticker_search'].apply(lambda x: pd.Series(get_stock_sector(x)))

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MRXF11.SA"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CPLE6.SA"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AMPB4.SA"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMIN.SA"}}}

In [17]:
list_tickers.to_excel('tickers.xlsx', index=False)

In [18]:
final_tickers = pd.read_excel('tickers.xlsx')
final_tickers

,ticker,asset,ticker_search,sector,industry
0,AAPL34,APPLE DRN,AAPL34.SA,Technology,Consumer Electronics
1,OXYP34,OCCIDENT PTR DRN,OXYP34.SA,Energy,Oil & Gas E&P
2,BERK34,BERKSHIRE DRN,BERK34.SA,Financial Services,Insurance - Diversified
3,BOAC34,BANK AMERICA DRN,BOAC34.SA,Financial Services,Banks - Diversified
4,AXPB34,AMERICAN EXP DRN,AXPB34.SA,Financial Services,Credit Services
...,...,...,...,...,...
61,CSNA3,SID NACIONAL ON,CSNA3.SA,Basic Materials,Steel
62,UGPA3,ULTRAPAR ON NM,UGPA3.SA,Energy,Oil & Gas Refining & Marketing
63,VBBR3,VIBRA ON NM,VBBR3.SA,Consumer Cyclical,Specialty Retail
64,WEGE3,WEG ON ED NM,WEGE3.SA,Industrials,Electrical Equipment & Parts
65,MBRF3,MARFRIG ON NM,MBRF3.SA,Consumer Defensive,Packaged Foods

In [22]:
final_tickers = final_tickers.rename(columns={'asset':'company_name'})
final_tickers

,ticker,company_name,sector,industry
0,AAPL34,APPLE DRN,Technology,Consumer Electronics
1,OXYP34,OCCIDENT PTR DRN,Energy,Oil & Gas E&P
2,BERK34,BERKSHIRE DRN,Financial Services,Insurance - Diversified
3,BOAC34,BANK AMERICA DRN,Financial Services,Banks - Diversified
4,AXPB34,AMERICAN EXP DRN,Financial Services,Credit Services
...,...,...,...,...
61,CSNA3,SID NACIONAL ON,Basic Materials,Steel
62,UGPA3,ULTRAPAR ON NM,Energy,Oil & Gas Refining & Marketing
63,VBBR3,VIBRA ON NM,Consumer Cyclical,Specialty Retail
64,WEGE3,WEG ON ED NM,Industrials,Electrical Equipment & Parts
65,MBRF3,MARFRIG ON NM,Consumer Defensive,Packaged Foods

In [23]:
from io import StringIO

buffer = StringIO()

final_tickers.to_csv(buffer, header=False, index=False)

buffer.seek(0)

columns = final_tickers.columns.to_list()

import pandas as pd
import numpy as np
import psycopg2
import os

# --- Configuration (Use your environment variables) ---
DB_HOST = os.environ.get("host")
DB_NAME = os.environ.get("dbname")
DB_USER = os.environ.get("user")
DB_PASSWORD = os.environ.get("password")
DB_PORT = 5432

connection = None
trades_df = pd.DataFrame() # Initialize an empty DataFrame

try:
    # 1. Establish the connection
    print(f"Connecting to the '{DB_NAME}' database...")
    connection = psycopg2.connect(
        host=DB_HOST,
        database=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD,
        port=DB_PORT
    )
    
except Exception as e:
    print(f"❌ Database connection or query error: {e}")
    trades_df = pd.DataFrame() # Ensure DF is empty on failure


try:
    with connection.cursor() as cur:
        cur.copy_from(
            file=buffer,
            table = 'assets',
            sep=",",
            columns=columns
        )

        connection.commit()
        print(f'Successfully inserted {len(final_tickers)} rows into trades table')

except Exception as e:
    connection.rollback()
    print(f'Database error: {e}')

Connecting to the 'postgres' database...
Successfully inserted 66 rows into trades table