In [2]:
import pandas as pd

In [8]:
file = pd.read_excel('dividends.xlsx', skiprows=13)
file

,Unnamed: 0,Movimentação,Liquidação,Lançamento,Unnamed: 4,Valor (R$),Saldo (R$)
0,NaN,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,NaN,-3512.32,204.72
1,NaN,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,NaN,3536,3717.04
2,NaN,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,NaN,0.01,181.04
3,NaN,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,NaN,0.03,181.03
4,NaN,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,NaN,2.38,181
5,NaN,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,NaN,3.45,178.62
6,NaN,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,NaN,0.85,175.17
7,NaN,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,NaN,0.43,174.32
8,NaN,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,NaN,-888.19,173.89
9,NaN,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,NaN,0.95,1062.08
10,NaN,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,NaN,3.85,1061.13
11,NaN,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,NaN,0.1,1057.28
12,NaN,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,NaN,0.39,1057.18
13,NaN,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,NaN,0.19,1056.79
14,NaN,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,NaN,0.21,1056.6
15,NaN,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,NaN,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Lançamentos futuros,NaN,NaN,NaN,NaN,NaN
18,NaN,Movimentação,Liquidação,Lançamento,NaN,Valor (R$),Saldo (R$)
19,NaN,NaN,NaN,Não há lançamentos para o período,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN,NaN
22,NaN,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Importante:\n,NaN,NaN,NaN,NaN,NaN
25,NaN,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN,NaN
26,NaN,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN,NaN
27,NaN,desatualizada.\n,NaN,NaN,NaN,NaN,NaN
28,NaN,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN,NaN
29,NaN,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN,NaN
30,NaN,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,"Atendimento ao cliente: +55 11 3003-5465, +55 ...",NaN,NaN
31,NaN,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN,NaN
32,NaN,SAO PAULO | SP,NaN,NaN,Ouvidoria: 0800-722-3730.,NaN,NaN
33,NaN,CEP: 04538-132,NaN,NaN,"Dias úteis, de segunda a sexta-feira, das 9h à...",NaN,NaN
34,NaN,CNPJ: 13.434.335/0001-60,NaN,NaN,https://www.rico.com.br/,NaN,NaN

In [13]:
file = file.iloc[:, [1,2,3,5,6]]
file

,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
0,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN
17,Lançamentos futuros,NaN,NaN,NaN,NaN
18,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
19,NaN,NaN,Não há lançamentos para o período,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN
22,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,Importante:\n,NaN,NaN,NaN,NaN
25,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN
26,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN
27,desatualizada.\n,NaN,NaN,NaN,NaN
28,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN
29,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN
30,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,NaN,NaN
31,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN
32,SAO PAULO | SP,NaN,NaN,NaN,NaN
33,CEP: 04538-132,NaN,NaN,NaN,NaN
34,CNPJ: 13.434.335/0001-60,NaN,NaN,NaN,NaN

In [14]:
file = file.rename(columns={'Valor (R$)': 'Movement'})
file

,Movimentação,Liquidação,Lançamento,Movement,Saldo (R$)
0,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN
17,Lançamentos futuros,NaN,NaN,NaN,NaN
18,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
19,NaN,NaN,Não há lançamentos para o período,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN
22,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,Importante:\n,NaN,NaN,NaN,NaN
25,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN
26,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN
27,desatualizada.\n,NaN,NaN,NaN,NaN
28,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN
29,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN
30,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,NaN,NaN
31,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN
32,SAO PAULO | SP,NaN,NaN,NaN,NaN
33,CEP: 04538-132,NaN,NaN,NaN,NaN
34,CNPJ: 13.434.335/0001-60,NaN,NaN,NaN,NaN

In [16]:
file.columns = ['movement_date', 'clearning_date','description','movement','balance']
file

,movement_date,clearning_date,description,movement,balance
0,2026-02-04 00:00:00,2026-02-06 00:00:00,OPERAÇÕES EM BOLSA PR 04/02/2026 NOTA Nº 12952...,-3512.32,204.72
1,2026-02-04 00:00:00,2026-02-04 00:00:00,Transferência recebida da conta digital,3536,3717.04
2,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES ITUB4 S/ ...,0.01,181.04
3,2026-02-02 00:00:00,2026-02-02 00:00:00,JUROS S/ CAPITAL DE CLIENTES BBDC4 S/ ...,0.03,181.03
4,2026-01-28 00:00:00,2026-01-28 00:00:00,JUROS S/ CAPITAL DE CLIENTES TAEE4 S/ ...,2.38,181
5,2026-01-28 00:00:00,2026-01-28 00:00:00,DIVIDENDOS DE CLIENTES TAEE4 S/ 20,3.45,178.62
6,2026-01-21 00:00:00,2026-01-21 00:00:00,JUROS S/ CAPITAL DE CLIENTES TIMS3 S/ ...,0.85,175.17
7,2026-01-21 00:00:00,2026-01-21 00:00:00,DIVIDENDOS DE CLIENTES OXYP34 S/ 3,0.43,174.32
8,2026-01-19 00:00:00,2026-01-21 00:00:00,OPERAÇÕES EM BOLSA PR 19/01/2026 NOTA Nº 12821...,-888.19,173.89
9,2026-01-19 00:00:00,2026-01-19 00:00:00,JUROS S/ CAPITAL DE CLIENTES CPLE3 S/ ...,0.95,1062.08
10,2026-01-15 00:00:00,2026-01-15 00:00:00,DIVIDENDOS DE CLIENTES MOOO34 S/ 1,3.85,1061.13
11,2026-01-14 00:00:00,2026-01-14 00:00:00,JUROS S/ CAPITAL DE CLIENTES EMBJ3 S/ ...,0.1,1057.28
12,2026-01-13 00:00:00,2026-01-13 00:00:00,JUROS S/ CAPITAL DE CLIENTES LREN3 S/ ...,0.39,1057.18
13,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.19,1056.79
14,2026-01-12 00:00:00,2026-01-12 00:00:00,JUROS S/ CAPITAL DE CLIENTES B3SA3 S/ ...,0.21,1056.6
15,2026-01-07 00:00:00,2026-01-09 00:00:00,OPERAÇÕES EM BOLSA PR 07/01/2026 NOTA Nº 12740...,987.46,1056.39
16,NaN,NaN,NaN,NaN,NaN
17,Lançamentos futuros,NaN,NaN,NaN,NaN
18,Movimentação,Liquidação,Lançamento,Valor (R$),Saldo (R$)
19,NaN,NaN,Não há lançamentos para o período,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,07 fev. 2026 - 16:28,NaN,NaN,NaN,NaN
22,"Extrato para simples conferência, sujeito a at...",NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,Importante:\n,NaN,NaN,NaN,NaN
25,Estas informações são confidenciais e destinad...,NaN,NaN,NaN,NaN
26,as informações são atualizadas em diferentes m...,NaN,NaN,NaN,NaN
27,desatualizada.\n,NaN,NaN,NaN,NaN
28,"Para reclamações, contate nossa Ouvidoria no t...",NaN,NaN,NaN,NaN
29,"Para acesso ao SAC, ligar para: 0800-774-0402.",NaN,NaN,NaN,NaN
30,RICO CORRETORA DE TITULOS E VALORES MOBILIARIO...,NaN,NaN,NaN,NaN
31,"AV. PRESIDENTE JUSCELINO KUBITSCHEK, 1909 | TO...",NaN,NaN,NaN,NaN
32,SAO PAULO | SP,NaN,NaN,NaN,NaN
33,CEP: 04538-132,NaN,NaN,NaN,NaN
34,CNPJ: 13.434.335/0001-60,NaN,NaN,NaN,NaN